name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-18.04
    env:
      LANG: en_AU.UTF-8
      GH_NAME: jshwi
      GH_EMAIL: stephen@jshwisolutions.com
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      CODECOV_SLUG: jshwi/borgini

    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - name: Checkout build
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: sudo apt install zstd libacl1-dev

    - name: Install Poetry
      run: |
        pip install --upgrade pip poetry

    - name: Cache Virtualenvs
      uses: actions/cache@v2
      id: pipenv-cache
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pipenv-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/Pipfile.lock') }}

    - name: Setup Virtualenv
      if: steps.pipenv-cache.outputs.cache-hit != 'true'
      run: |
        poetry install

    - name: Audit
      run: |
        poetry run pyaud audit --deploy --rcfile .github/pyaud.toml
